const localDataBase = {
  LEVEL: [
    {
      idLevel: 1,
      nameLevel: "DIRECTOR",
    },
    {
      idLevel: 2,
      nameLevel: "TEACHER",
    },
    {
      idLevel: 3,
      nameLevel: "SECRETARY",
    },
    {
      idLevel: 4,
      nameLevel: "STUDENT",
    },
  ],
  EXTENSION: [
    {
      idExtension: 1,
      departament: "LP",
    },
    {
      idExtension: 2,
      departament: "CHQ",
    },
    {
      idExtension: 3,
      departament: "CBBA",
    },
    {
      idExtension: 4,
      departament: "OR",
    },
    {
      idExtension: 5,
      departament: "PT",
    },
    {
      idExtension: 6,
      departament: "TJA",
    },
    {
      idExtension: 7,
      departament: "SC",
    },
    {
      idExtension: 8,
      departament: "BN",
    },
    {
      idExtension: 9,
      departament: "PD",
    },
  ],
  STAFF: [
    {
      idStaff: 1,
      idLevel: 1,
      idExtension: 3,
      nameStaff: "Rafael",
      lastNameStaff: "Choque Perez",
      emailStaff: "rafael@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Viva",
      dateBirthStaff: "1905-06-10",
      carnetStaff: 8349,
      photoStaff:
        "https://www.suzuki.com.bo/media/fvli4nhu/foto_0000009420220526152924_turquesa.png",
      stateStaff: true,
    },
    {
      idStaff: 2,
      idLevel: 1,
      idExtension: 1,
      nameStaff: "Isaura",
      lastNameStaff: "Quispe Mamani",
      emailStaff: "isa@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Viva La vida",
      dateBirthStaff: "1985-01-19",
      carnetStaff: 8346,
      photoStaff:
        "https://i.pinimg.com/236x/eb/04/d5/eb04d5c9528ff994e31c513ccc1a77a7.jpg",
      stateStaff: true,
    },
    {
      idStaff: 3,
      idLevel: 2,
      idExtension: 5,
      nameStaff: "Bernalt",
      lastNameStaff: "Vaca Loca",
      emailStaff: "bvl@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Viva :D",
      dateBirthStaff: "1999-10-27",
      carnetStaff: 831,
      photoStaff:
        "https://i.pinimg.com/236x/e4/42/5a/e4425aad73f01d36ace4c86c3156dcdc.jpg",
      stateStaff: false,
    },
    {
      idStaff: 4,
      idLevel: 2,
      idExtension: 6,
      nameStaff: "Rambo",
      lastNameStaff: "Ramirez Rojas",
      emailStaff: "rambo@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Guerra",
      dateBirthStaff: "1999-10-21",
      carnetStaff: 8365,
      photoStaff:
        "https://i.pinimg.com/236x/50/5f/86/505f86e1308879fe486807d220060313.jpg",
      stateStaff: true,
    },
    {
      idStaff: 5,
      idLevel: 2,
      idExtension: 5,
      nameStaff: "Silvia",
      lastNameStaff: "Chavez Ajata",
      emailStaff: "silvia@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Roja",
      dateBirthStaff: "1995-07-18",
      carnetStaff: 832,
      photoStaff:
        "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-2.jpg",
      stateStaff: true,
    },
    {
      idStaff: 6,
      idLevel: 2,
      idExtension: 6,
      nameStaff: "Madelein",
      lastNameStaff: "Flores Achu",
      emailStaff: "made@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Inser into",
      dateBirthStaff: "2000-08-27",
      carnetStaff: 8302,
      photoStaff:
        "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-11.jpg",
      stateStaff: true,
    },
    {
      idStaff: 7,
      idLevel: 3,
      idExtension: 9,
      nameStaff: "Alejandra",
      lastNameStaff: "Gutierrez Pari",
      emailStaff: "ale@gmail.com",
      passwordStaff: "*********",
      addressStaff: "z. Cruce Viacha",
      dateBirthStaff: "2003-04-24",
      carnetStaff: 8390,
      photoStaff:
        "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-wakanda.jpg",
      stateStaff: false,
    },
  ],
  HOURS: [
    {
      idHours: 1,
      startTime: "8:00",
      endTime: "10:00",
      totalTime: "2:00",
      stateHours: true,
    },
    {
      idHours: 2,
      startTime: "8:30",
      endTime: "10:30",
      totalTime: "2:00",
      stateHours: true,
    },
    {
      idHours: 3,
      startTime: "12:00",
      endTime: "13:00",
      totalTime: "1:00",
      stateHours: false,
    },
    {
      idHours: 4,
      startTime: "13:20",
      endTime: "15:20",
      totalTime: "2:00",
      stateHours: true,
    },
  ],
  TYPECLASS: [
    {
      idTypeClass: 1,
      nameClass: "Caporal",
    },
    {
      idTypeClass: 2,
      nameClass: "Tinku",
    },
    {
      idTypeClass: 3,
      nameClass: "Cumbia",
    },
    {
      idTypeClass: 4,
      nameClass: "Rock and roll",
    },
  ],
  CLASS: [
    {
      idClass: 1,
      idHours: 1,
      idStaff: 3,
      idTypeClass: 1,
      parallel: "2B",
      stateClass: true,
    },
    {
      idClass: 2,
      idHours: 2,
      idStaff: 34,
      idTypeClass: 1,
      parallel: "2A",
      stateClass: true,
    },
    {
      idClass: 3,
      idHours: 1,
      idStaff: 5,
      idTypeClass: 3,
      parallel: "1A",
      stateClass: true,
    },
    {
      idClass: 4,
      idHours: 3,
      idStaff: 6,
      idTypeClass: 4,
      parallel: "1B",
      stateClass: true,
    },
  ],
  STUDENT: [
    {
      idStudent: 10,
      idLevel: 4,
      idExtension: 9,
      nameStudent: "Mireya",
      lastNameStudent: "Pereira Chavaria",
      emailStudent: "mireya@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 789562,
      addressStudent: "Z. Belleza",
      dateBirthStudent: "2000/08/27",
      codeStudent: "MPC-789",
      photoStudent:
        "https://www.animaker.es/blog/wp-content/uploads/2023/08/Lt_lola-300x260.webp",
      stateStudent: true,
    },
    {
      idStudent: 15,
      idLevel: 4,
      idExtension: 8,
      nameStudent: "Elisa",
      lastNameStudent: "Chavez Ajata",
      emailStudent: "elisa@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 985654,
      addressStudent: "Z. Buenos Aires",
      dateBirthStudent: "2003/05/17",
      codeStudent: "ECA-985",
      photoStudent:
        "https://www.animaker.es/blog/wp-content/uploads/2023/08/Angelica_Pickles-260x300.webp",
      stateStudent: true,
    },
    {
      idStudent: 32,
      idLevel: 4,
      idExtension: 7,
      nameStudent: "Willy",
      lastNameStudent: "Olshon Mccmaon",
      emailStudent: "willy@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 162132,
      addressStudent: "Z. Wall Grounp",
      dateBirthStudent: "2005/02/16",
      codeStudent: "WOM-162",
      photoStudent:
        "https://www.animaker.es/blog/wp-content/uploads/2023/08/Space_Ghost-640x400-1-300x188.webp",
      stateStudent: true,
    },
    {
      idStudent: 52,
      idLevel: 4,
      idExtension: 6,
      nameStudent: "Nelly",
      lastNameStudent: "Baldes Roque",
      emailStudent: "nelly@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 65478,
      addressStudent: "Z. Siempre viva",
      dateBirthStudent: "2008/03/01",
      codeStudent: "NBR-684",
      photoStudent:
        "https://elcomercio.pe/resizer/gX41x2jmnCd_GVbLC0q_9R8v4XA=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/L7WIEAYMKZEYVO6V27TLPCIJBM.jpg",
      stateStudent: true,
    },
    {
      idStudent: 80,
      idLevel: 4,
      idExtension: 3,
      nameStudent: "Laura",
      lastNameStudent: "Ingllas Mamani",
      emailStudent: "laura@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 97106,
      addressStudent: "Z. Lomas",
      dateBirthStudent: "2010/01/19",
      codeStudent: "LIM-971",
      photoStudent:
        "https://elcomercio.pe/resizer/5esvf6D0kfLDmCod0hqSvpGd-Wo=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/VKFPPQASPBHAFOYBJOSMJKSNZI.jpg",
      stateStudent: true,
    },
    {
      idStudent: 99,
      idLevel: 4,
      idExtension: 1,
      nameStudent: "Genesis",
      lastNameStudent: "Sue Anderson",
      emailStudent: "sue@gmail.com",
      passwordStudent: "***********",
      carnetStudent: 496540,
      addressStudent: "Z. La mas linda",
      dateBirthStudent: "2003/04/28",
      codeStudent: "GSA-496",
      photoStudent:
        "https://elcomercio.pe/resizer/1Xlr_I0q1y7jQ8jqAoEggL3YMpA=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/VZZDRW56ZNFAXLL7XPW72L4P3Q.jpg",
      stateStudent: true,
    },
  ],
  PAYMENT: [
    {
      idStudent: 10,
      idClass: 1,
      paymentDate: "2024/01/03",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 15,
      idClass: 1,
      paymentDate: "2024/01/04",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 32,
      idClass: 2,
      paymentDate: "2024/01/04",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 52,
      idClass: 2,
      paymentDate: "2024/01/05",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 80,
      idClass: 3,
      paymentDate: "2024/01/05",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 99,
      idClass: 1,
      paymentDate: "2024/01/05",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 10,
      idClass: 1,
      paymentDate: "2024/02/10",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 15,
      idClass: 1,
      paymentDate: "2024/02/10",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 32,
      idClass: 2,
      paymentDate: "2024/02/10",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 52,
      idClass: 2,
      paymentDate: "2024/02/11",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 80,
      idClass: 2,
      paymentDate: "2024/02/14",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 99,
      idClass: 1,
      paymentDate: "2024/02/10",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 10,
      idClass: 1,
      paymentDate: "2024/03/05",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 15,
      idClass: 1,
      paymentDate: "2024/03/05",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 32,
      idClass: 2,
      paymentDate: "2024/03/06",
      onAccount: 0.0,
      debt: 0.0,
      total: 150.0,
    },
    {
      idStudent: 52,
      idClass: 2,
      paymentDate: "2024/03/08",
      onAccount: 80.0,
      debt: 70.0,
      total: 150.0,
    },
    {
      idStudent: 80,
      idClass: 2,
      paymentDate: "2024/03/08",
      onAccount: 50.0,
      debt: 100.0,
      total: 150.0,
    },
    {
      idStudent: 99,
      idClass: 1,
      paymentDate: "2024/03/09",
      onAccount: 60.0,
      debt: 90.0,
      total: 150.0,
    },
  ],
  QUALIFICATION: [
    {
      idClass: 1,
      idStudent: 10,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 90.0,
    },
    {
      idClass: 1,
      idStudent: 15,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 50.0,
    },
    {
      idClass: 1,
      idStudent: 32,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 70.0,
    },
    {
      idClass: 2,
      idStudent: 52,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 60.0,
    },
    {
      idClass: 3,
      idStudent: 80,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 80.0,
    },
    {
      idClass: 1,
      idStudent: 99,
      notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
      average: 86.0,
    },
  ],
  ASSISTANCE: [
    {
      idStudent: 10,
      idClass: 1,
      record: { "2024/02/10": true, "2024/02/11": false, "2024/02/12": true },
    },
    {
      idStudent: 15,
      idClass: 1,
      record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
    },
    {
      idStudent: 32,
      idClass: 2,
      record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
    },
    {
      idStudent: 52,
      idClass: 2,
      record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
    },
    {
      idStudent: 80,
      idClass: 3,
      record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
    },
    {
      idStudent: 99,
      idClass: 1,
      record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
    },
  ],
};

const LEVEL = [
  {
    idLevel: 1,
    nameLevel: "DIRECTOR",
  },
  {
    idLevel: 2,
    nameLevel: "TEACHER",
  },
  {
    idLevel: 3,
    nameLevel: "SECRETARY",
  },
  {
    idLevel: 4,
    nameLevel: "STUDENT",
  },
];

const EXTENSION = [
  {
    idExtension: 1,
    departament: "LP",
  },
  {
    idExtension: 2,
    departament: "CHQ",
  },
  {
    idExtension: 3,
    departament: "CBBA",
  },
  {
    idExtension: 4,
    departament: "OR",
  },
  {
    idExtension: 5,
    departament: "PT",
  },
  {
    idExtension: 6,
    departament: "TJA",
  },
  {
    idExtension: 7,
    departament: "SC",
  },
  {
    idExtension: 8,
    departament: "BN",
  },
  {
    idExtension: 9,
    departament: "PD",
  },
];

const STAFF = [
  {
    idStaff: 1,
    idLevel: 1,
    idExtension: 3,
    nameStaff: "Rafael",
    lastNameStaff: "Choque Perez",
    emailStaff: "rafael@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Viva",
    dateBirthStaff: "1905-06-10",
    carnetStaff: 8349,
    photoStaff:
      "https://www.suzuki.com.bo/media/fvli4nhu/foto_0000009420220526152924_turquesa.png",
    stateStaff: true,
  },
  {
    idStaff: 2,
    idLevel: 1,
    idExtension: 1,
    nameStaff: "Isaura",
    lastNameStaff: "Quispe Mamani",
    emailStaff: "isa@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Viva La vida",
    dateBirthStaff: "1985-01-19",
    carnetStaff: 8346,
    photoStaff:
      "https://i.pinimg.com/236x/eb/04/d5/eb04d5c9528ff994e31c513ccc1a77a7.jpg",
    stateStaff: true,
  },
  {
    idStaff: 3,
    idLevel: 2,
    idExtension: 5,
    nameStaff: "Bernalt",
    lastNameStaff: "Vaca Loca",
    emailStaff: "bvl@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Viva :D",
    dateBirthStaff: "1999-10-27",
    carnetStaff: 831,
    photoStaff:
      "https://i.pinimg.com/236x/e4/42/5a/e4425aad73f01d36ace4c86c3156dcdc.jpg",
    stateStaff: false,
  },
  {
    idStaff: 4,
    idLevel: 2,
    idExtension: 6,
    nameStaff: "Rambo",
    lastNameStaff: "Ramirez Rojas",
    emailStaff: "rambo@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Guerra",
    dateBirthStaff: "1999-10-21",
    carnetStaff: 8365,
    photoStaff:
      "https://i.pinimg.com/236x/50/5f/86/505f86e1308879fe486807d220060313.jpg",
    stateStaff: true,
  },
  {
    idStaff: 5,
    idLevel: 2,
    idExtension: 5,
    nameStaff: "Silvia",
    lastNameStaff: "Chavez Ajata",
    emailStaff: "silvia@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Roja",
    dateBirthStaff: "1995-07-18",
    carnetStaff: 832,
    photoStaff:
      "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-2.jpg",
    stateStaff: true,
  },
  {
    idStaff: 6,
    idLevel: 2,
    idExtension: 6,
    nameStaff: "Madelein",
    lastNameStaff: "Flores Achu",
    emailStaff: "made@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Inser into",
    dateBirthStaff: "2000-08-27",
    carnetStaff: 8302,
    photoStaff:
      "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-11.jpg",
    stateStaff: true,
  },
  {
    idStaff: 7,
    idLevel: 3,
    idExtension: 9,
    nameStaff: "Alejandra",
    lastNameStaff: "Gutierrez Pari",
    emailStaff: "ale@gmail.com",
    passwordStaff: "*********",
    addressStaff: "z. Cruce Viacha",
    dateBirthStaff: "2003-04-24",
    carnetStaff: 8390,
    photoStaff:
      "http://www.redcapitalmx.com/wp-content/uploads/2018/04/Avengers-wakanda.jpg",
    stateStaff: false,
  },
];

const HOURS = [
  {
    idHours: 1,
    startTime: "8:00",
    endTime: "10:00",
    totalTime: "2:00",
    stateHours: true,
  },
  {
    idHours: 2,
    startTime: "8:30",
    endTime: "10:30",
    totalTime: "2:00",
    stateHours: true,
  },
  {
    idHours: 3,
    startTime: "12:00",
    endTime: "13:00",
    totalTime: "1:00",
    stateHours: false,
  },
  {
    idHours: 4,
    startTime: "13:20",
    endTime: "15:20",
    totalTime: "2:00",
    stateHours: true,
  },
];

const TYPECLASS = [
  {
    idTypeClass: 1,
    nameClass: "Caporal",
  },
  {
    idTypeClass: 2,
    nameClass: "Tinku",
  },
  {
    idTypeClass: 3,
    nameClass: "Cumbia",
  },
  {
    idTypeClass: 4,
    nameClass: "Rock and roll",
  },
];

const CLASS = [
  {
    idClass: 1,
    idHours: 1,
    idStaff: 3,
    idTypeClass: 1,
    parallel: "2B",
    stateClass: true,
  },
  {
    idClass: 2,
    idHours: 2,
    idStaff: 34,
    idTypeClass: 1,
    parallel: "2A",
    stateClass: true,
  },
  {
    idClass: 3,
    idHours: 1,
    idStaff: 5,
    idTypeClass: 3,
    parallel: "1A",
    stateClass: true,
  },
  {
    idClass: 4,
    idHours: 3,
    idStaff: 6,
    idTypeClass: 4,
    parallel: "1B",
    stateClass: true,
  },
];

const STUDENT = [
  {
    idStudent: 10,
    idLevel: 4,
    idExtension: 9,
    nameStudent: "Mireya",
    lastNameStudent: "Pereira Chavaria",
    emailStudent: "mireya@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 789562,
    addressStudent: "Z. Belleza",
    dateBirthStudent: "2000/08/27",
    codeStudent: "MPC-789",
    photoStudent:
      "https://www.animaker.es/blog/wp-content/uploads/2023/08/Lt_lola-300x260.webp",
    stateStudent: true,
  },
  {
    idStudent: 15,
    idLevel: 4,
    idExtension: 8,
    nameStudent: "Elisa",
    lastNameStudent: "Chavez Ajata",
    emailStudent: "elisa@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 985654,
    addressStudent: "Z. Buenos Aires",
    dateBirthStudent: "2003/05/17",
    codeStudent: "ECA-985",
    photoStudent:
      "https://www.animaker.es/blog/wp-content/uploads/2023/08/Angelica_Pickles-260x300.webp",
    stateStudent: true,
  },
  {
    idStudent: 32,
    idLevel: 4,
    idExtension: 7,
    nameStudent: "Willy",
    lastNameStudent: "Olshon Mccmaon",
    emailStudent: "willy@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 162132,
    addressStudent: "Z. Wall Grounp",
    dateBirthStudent: "2005/02/16",
    codeStudent: "WOM-162",
    photoStudent:
      "https://www.animaker.es/blog/wp-content/uploads/2023/08/Space_Ghost-640x400-1-300x188.webp",
    stateStudent: true,
  },
  {
    idStudent: 52,
    idLevel: 4,
    idExtension: 6,
    nameStudent: "Nelly",
    lastNameStudent: "Baldes Roque",
    emailStudent: "nelly@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 65478,
    addressStudent: "Z. Siempre viva",
    dateBirthStudent: "2008/03/01",
    codeStudent: "NBR-684",
    photoStudent:
      "https://elcomercio.pe/resizer/gX41x2jmnCd_GVbLC0q_9R8v4XA=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/L7WIEAYMKZEYVO6V27TLPCIJBM.jpg",
    stateStudent: true,
  },
  {
    idStudent: 80,
    idLevel: 4,
    idExtension: 3,
    nameStudent: "Laura",
    lastNameStudent: "Ingllas Mamani",
    emailStudent: "laura@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 97106,
    addressStudent: "Z. Lomas",
    dateBirthStudent: "2010/01/19",
    codeStudent: "LIM-971",
    photoStudent:
      "https://elcomercio.pe/resizer/5esvf6D0kfLDmCod0hqSvpGd-Wo=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/VKFPPQASPBHAFOYBJOSMJKSNZI.jpg",
    stateStudent: true,
  },
  {
    idStudent: 99,
    idLevel: 4,
    idExtension: 1,
    nameStudent: "Genesis",
    lastNameStudent: "Sue Anderson",
    emailStudent: "sue@gmail.com",
    passwordStudent: "***********",
    carnetStudent: 496540,
    addressStudent: "Z. La mas linda",
    dateBirthStudent: "2003/04/28",
    codeStudent: "GSA-496",
    photoStudent:
      "https://elcomercio.pe/resizer/1Xlr_I0q1y7jQ8jqAoEggL3YMpA=/620x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/VZZDRW56ZNFAXLL7XPW72L4P3Q.jpg",
    stateStudent: true,
  },
];

const PAYMENT = [
  {
    idStudent: 10,
    idClass: 1,
    paymentDate: "2024/01/03",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 15,
    idClass: 1,
    paymentDate: "2024/01/04",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 32,
    idClass: 2,
    paymentDate: "2024/01/04",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 52,
    idClass: 2,
    paymentDate: "2024/01/05",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 80,
    idClass: 3,
    paymentDate: "2024/01/05",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 99,
    idClass: 1,
    paymentDate: "2024/01/05",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 10,
    idClass: 1,
    paymentDate: "2024/02/10",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 15,
    idClass: 1,
    paymentDate: "2024/02/10",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 32,
    idClass: 2,
    paymentDate: "2024/02/10",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 52,
    idClass: 2,
    paymentDate: "2024/02/11",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 80,
    idClass: 2,
    paymentDate: "2024/02/14",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 99,
    idClass: 1,
    paymentDate: "2024/02/10",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 10,
    idClass: 1,
    paymentDate: "2024/03/05",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 15,
    idClass: 1,
    paymentDate: "2024/03/05",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 32,
    idClass: 2,
    paymentDate: "2024/03/06",
    onAccount: 0.0,
    debt: 0.0,
    total: 150.0,
  },
  {
    idStudent: 52,
    idClass: 2,
    paymentDate: "2024/03/08",
    onAccount: 80.0,
    debt: 70.0,
    total: 150.0,
  },
  {
    idStudent: 80,
    idClass: 2,
    paymentDate: "2024/03/08",
    onAccount: 50.0,
    debt: 100.0,
    total: 150.0,
  },
  {
    idStudent: 99,
    idClass: 1,
    paymentDate: "2024/03/09",
    onAccount: 60.0,
    debt: 90.0,
    total: 150.0,
  },
];

const QUALIFICATION = [
  {
    idClass: 1,
    idStudent: 10,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 90.0,
  },
  {
    idClass: 1,
    idStudent: 15,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 50.0,
  },
  {
    idClass: 1,
    idStudent: 32,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 70.0,
  },
  {
    idClass: 2,
    idStudent: 52,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 60.0,
  },
  {
    idClass: 3,
    idStudent: 80,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 80.0,
  },
  {
    idClass: 1,
    idStudent: 99,
    notes: { "1P": 90.0, "2P": 85.0, "3P": 76.0 },
    average: 86.0,
  },
];

const ASSISTANCE = [
  {
    idStudent: 10,
    idClass: 1,
    record: { "2024/02/10": true, "2024/02/11": false, "2024/02/12": true },
  },
  {
    idStudent: 15,
    idClass: 1,
    record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
  },
  {
    idStudent: 32,
    idClass: 2,
    record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
  },
  {
    idStudent: 52,
    idClass: 2,
    record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
  },
  {
    idStudent: 80,
    idClass: 3,
    record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
  },
  {
    idStudent: 99,
    idClass: 1,
    record: { "2024/02/10": true, "2024/02/11": true, "2024/02/12": true },
  },
];

module.exports = {
  localDataBase,
  LEVEL,
  EXTENSION,
  STAFF,
  HOURS,
  TYPECLASS,
  CLASS,
  STUDENT,
  PAYMENT,
  QUALIFICATION,
  ASSISTANCE,
};
